/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shivs2' at '13/1/19 12:22 AM' with Gradle 2.14.1
 *
 * @author shivs2, @date 13/1/19 12:22 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
